Repository jenkinsci/ivy-plugin, pull requests merged in 2025-03, with the labels that each got.

#128 Reduce EE 8 compatibility layer
  src/main/java/hudson/ivy/IvyReporterDescriptor.java
Labels: internal

#131 Enable automated release
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: enhancement

#132 Migrate tests to JUnit5
  pom.xml
  src/test/java/hudson/ivy/IvyBuildTriggerTest.java
  src/test/java/hudson/ivy/IvyModuleSetTest.java
Labels: test

#133 Migrate to EE 9 in Jelly views
  src/main/resources/hudson/ivy/IvyModule/actions.jelly
  src/main/resources/hudson/ivy/IvyModuleSet/actions.jelly
Labels: enhancement
